# <font color=blue>Assignments for "Data Cleaning - Missing Values"</font>

In this assignment, you are going to use a dataset related to the US education system. Please download the ([dataset](https://www.kaggle.com/noriuk/us-education-datasets-unification-project/home)) from Kaggle. You are going to use `states_all.csv` within this dataset.

To complete this assignment, submit the Github link of the Jupyter notebook file containing solutions to the questions below. You can talk to your mentor on your head or ask Slack at office time.

**(1)** Find the types of variables in the dataset and the missing (null) ratio of each variable.

In [1]:
import pandas as pd
import numpy as np
states = pd.read_csv("E:/user/Notebooks/data/states_all.csv")
states.drop(states[states.YEAR < 1992].index, inplace=True)
states.drop(states[states.YEAR > 2016].index, inplace=True)

states.isnull().sum()*100/len(states)

PRIMARY_KEY                      0.000000
STATE                            0.000000
YEAR                             0.000000
ENROLL                           5.918524
TOTAL_REVENUE                    1.998463
FEDERAL_REVENUE                  1.998463
STATE_REVENUE                    1.998463
LOCAL_REVENUE                    1.998463
TOTAL_EXPENDITURE                1.998463
INSTRUCTION_EXPENDITURE          1.998463
SUPPORT_SERVICES_EXPENDITURE     1.998463
OTHER_EXPENDITURE                5.918524
CAPITAL_OUTLAY_EXPENDITURE       1.998463
GRADES_PK_G                      2.997694
GRADES_KG_G                      1.998463
GRADES_4_G                       1.998463
GRADES_8_G                       1.998463
GRADES_12_G                      1.998463
GRADES_1_8_G                    21.598770
GRADES_9_12_G                   21.598770
GRADES_ALL_G                     1.998463
AVG_MATH_4_SCORE                64.796311
AVG_MATH_8_SCORE                64.873174
AVG_READING_4_SCORE             58.186011
AVG_READING_8_SCORE             64.950038
dtype: float64

**(2)** You may have noticed that our data has a year column. For now, forget about the year data and assume that each observation was made in the same year. Consider how you can fill in missing values for each variable. Filling in the missing values with a value is meaningful for which variables and for which ones?

In [2]:
from pandas.api.types import is_numeric_dtype

def fix_missing(df, col, name):
    if is_numeric_dtype(col):
        df[name] = col.fillna(col.median())
        
    
    
for name, col in states.items():
    fix_missing(states, col, name)
    
  
states.isnull().sum()*100/len(states)

PRIMARY_KEY                     0.0
STATE                           0.0
YEAR                            0.0
ENROLL                          0.0
TOTAL_REVENUE                   0.0
FEDERAL_REVENUE                 0.0
STATE_REVENUE                   0.0
LOCAL_REVENUE                   0.0
TOTAL_EXPENDITURE               0.0
INSTRUCTION_EXPENDITURE         0.0
SUPPORT_SERVICES_EXPENDITURE    0.0
OTHER_EXPENDITURE               0.0
CAPITAL_OUTLAY_EXPENDITURE      0.0
GRADES_PK_G                     0.0
GRADES_KG_G                     0.0
GRADES_4_G                      0.0
GRADES_8_G                      0.0
GRADES_12_G                     0.0
GRADES_1_8_G                    0.0
GRADES_9_12_G                   0.0
GRADES_ALL_G                    0.0
AVG_MATH_4_SCORE                0.0
AVG_MATH_8_SCORE                0.0
AVG_READING_4_SCORE             0.0
AVG_READING_8_SCORE             0.0
dtype: float64

**(3)** Now it's time to consider the factor of time! Review your answer in question 2 and fill in the missing data based on the values observed during that year. For example, if you want to fill a value with an average value, calculate the average of that year.

In [19]:
states = pd.read_csv("E:/user/Notebooks/data/states_all.csv")
states.drop(states[states.YEAR < 1992].index, inplace=True)
states.drop(states[states.YEAR > 2016].index, inplace=True)


for name, col in states.items():
    for j in states.YEAR.unique():
        if is_numeric_dtype(col):
            states[name] = col.fillna(col.groupby(states.YEAR==j).transform('mean'))
    
states

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,922462.074844,2.678885e+06,3.041770e+05,1.659028e+06,7.156800e+05,2.653798e+06,1.481703e+06,...,57948.000000,58025.000000,41167.000000,577954.717647,281331.857843,7.316340e+05,208.000000,252.000000,207.000000,260.0
1,1992_ALASKA,ALASKA,1992,922462.074844,1.049591e+06,1.067800e+05,7.207110e+05,2.221000e+05,9.724880e+05,4.983620e+05,...,9748.000000,8789.000000,6714.000000,577954.717647,281331.857843,1.224870e+05,218.418605,266.325581,215.372093,260.0
2,1992_ARIZONA,ARIZONA,1992,922462.074844,3.258079e+06,2.978880e+05,1.369815e+06,1.590376e+06,3.401580e+06,1.435908e+06,...,55433.000000,49081.000000,37410.000000,577954.717647,281331.857843,6.734770e+05,215.000000,265.000000,209.000000,260.0
3,1992_ARKANSAS,ARKANSAS,1992,922462.074844,1.711959e+06,1.785710e+05,9.587850e+05,5.746030e+05,1.743022e+06,9.643230e+05,...,34632.000000,36011.000000,27651.000000,577954.717647,281331.857843,4.414900e+05,210.000000,256.000000,211.000000,260.0
4,1992_CALIFORNIA,CALIFORNIA,1992,922462.074844,2.626002e+07,2.072470e+06,1.654651e+07,7.641041e+06,2.713883e+07,1.435892e+07,...,418418.000000,363296.000000,270675.000000,577954.717647,281331.857843,5.254844e+06,208.000000,261.000000,202.000000,260.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1655,2011_NATIONAL,NATIONAL,2011,917541.566176,9.290765e+06,7.873945e+05,4.312719e+06,4.190651e+06,9.395936e+06,4.864428e+06,...,71118.763072,70943.346405,60541.701797,577954.717647,281331.857843,9.430825e+05,241.000000,284.000000,221.000000,265.0
1656,2013_DODEA,DODEA,2013,917541.566176,9.290765e+06,7.873945e+05,4.312719e+06,4.190651e+06,9.395936e+06,4.864428e+06,...,71118.763072,70943.346405,60541.701797,577954.717647,281331.857843,9.430825e+05,245.000000,290.000000,232.000000,277.0
1657,2013_NATIONAL,NATIONAL,2013,917541.566176,9.290765e+06,7.873945e+05,4.312719e+06,4.190651e+06,9.395936e+06,4.864428e+06,...,71118.763072,70943.346405,60541.701797,577954.717647,281331.857843,9.430825e+05,242.000000,285.000000,222.000000,268.0
1658,2015_DODEA,DODEA,2015,917541.566176,9.290765e+06,7.873945e+05,4.312719e+06,4.190651e+06,9.395936e+06,4.864428e+06,...,71118.763072,70943.346405,60541.701797,577954.717647,281331.857843,9.430825e+05,248.000000,291.000000,234.000000,277.0
1659,2015_NATIONAL,NATIONAL,2015,917541.566176,9.290765e+06,7.873945e+05,4.312719e+06,4.190651e+06,9.395936e+06,4.864428e+06,...,71118.763072,70943.346405,60541.701797,577954.717647,281331.857843,9.430825e+05,240.000000,282.000000,223.000000,265.0

**(4)** This time, fill in the missing values by interpolating.

In [20]:
states.interpolate(method ='linear', limit_direction ='forward') .head(20)

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,922462.074844,2678885.0,304177.0,1659028.0,715680.0,2653798.0,1481703.0,...,57948.0,58025.0,41167.0,577954.717647,281331.857843,731634.0,208.000000,252.000000,207.000000,260.0
1,1992_ALASKA,ALASKA,1992,922462.074844,1049591.0,106780.0,720711.0,222100.0,972488.0,498362.0,...,9748.0,8789.0,6714.0,577954.717647,281331.857843,122487.0,218.418605,266.325581,215.372093,260.0
2,1992_ARIZONA,ARIZONA,1992,922462.074844,3258079.0,297888.0,1369815.0,1590376.0,3401580.0,1435908.0,...,55433.0,49081.0,37410.0,577954.717647,281331.857843,673477.0,215.000000,265.000000,209.000000,260.0
3,1992_ARKANSAS,ARKANSAS,1992,922462.074844,1711959.0,178571.0,958785.0,574603.0,1743022.0,964323.0,...,34632.0,36011.0,27651.0,577954.717647,281331.857843,441490.0,210.000000,256.000000,211.000000,260.0
4,1992_CALIFORNIA,CALIFORNIA,1992,922462.074844,26260025.0,2072470.0,16546514.0,7641041.0,27138832.0,14358922.0,...,418418.0,363296.0,270675.0,577954.717647,281331.857843,5254844.0,208.000000,261.000000,202.000000,260.0
5,1992_COLORADO,COLORADO,1992,922462.074844,3185173.0,163253.0,1307986.0,1713934.0,3264826.0,1642466.0,...,50648.0,45025.0,34533.0,577954.717647,281331.857843,612635.0,221.000000,272.000000,217.000000,260.0
6,1992_CONNECTICUT,CONNECTICUT,1992,922462.074844,3834302.0,143542.0,1342539.0,2348221.0,3721338.0,2148041.0,...,38058.0,33691.0,28366.0,577954.717647,281331.857843,488476.0,227.000000,274.000000,222.000000,260.0
7,1992_DELAWARE,DELAWARE,1992,922462.074844,645233.0,45945.0,420942.0,178346.0,638784.0,372722.0,...,8272.0,8012.0,6129.0,577954.717647,281331.857843,104321.0,218.000000,263.000000,213.000000,260.0
8,1992_DISTRICT_OF_COLUMBIA,DISTRICT_OF_COLUMBIA,1992,922462.074844,709480.0,64749.0,0.0,644731.0,742893.0,329160.0,...,5832.0,5000.0,3433.0,577954.717647,281331.857843,80937.0,193.000000,235.000000,188.000000,260.0
9,1992_FLORIDA,FLORIDA,1992,922462.074844,11506299.0,788420.0,5683949.0,5033930.0,11305642.0,5166374.0,...,164416.0,142372.0,100835.0,577954.717647,281331.857843,1981407.0,214.000000,260.000000,208.000000,260.0
10,1992_GEORGIA,GEORGIA,1992,922462.074844,5536901.0,398701.0,2798674.0,2339526.0,5535942.0,3043984.0,...,99648.0,92374.0,63646.0,577954.717647,281331.857843,1207186.0,216.000000,259.000000,212.000000,260.0
11,1992_HAWAII,HAWAII,1992,922462.074844,996809.0,71273.0,903443.0,22093.0,1040121.0,536115.0,...,13754.0,11750.0,9051.0,577954.717647,281331.857843,177448.0,214.000000,257.000000,203.000000,260.0
12,1992_IDAHO,IDAHO,1992,922462.074844,859329.0,69138.0,531912.0,258279.0,886161.0,473505.0,...,18607.0,18880.0,14593.0,577954.717647,281331.857843,231668.0,222.000000,275.000000,219.000000,260.0
13,1992_ILLINOIS,ILLINOIS,1992,922462.074844,9748650.0,597077.0,3073178.0,6078395.0,9850560.0,5010400.0,...,133120.0,134317.0,106475.0,577954.717647,281331.857843,1873567.0,218.418605,266.325581,215.372093,260.0
14,1992_INDIANA,INDIANA,1992,922462.074844,5060274.0,257044.0,2578149.0,2225081.0,5182754.0,2598925.0,...,73760.0,75477.0,62234.0,577954.717647,281331.857843,960630.0,221.000000,270.000000,221.000000,260.0
15,1992_IOWA,IOWA,1992,922462.074844,2663934.0,125665.0,1176205.0,1362064.0,2795774.0,1446478.0,...,37692.0,36892.0,33057.0,577954.717647,281331.857843,494839.0,230.000000,283.000000,225.000000,260.0
16,1992_KANSAS,KANSAS,1992,922462.074844,2245348.0,121625.0,903199.0,1220524.0,2234915.0,1165749.0,...,36013.0,33288.0,26706.0,577954.717647,281331.857843,451536.0,218.418605,266.325581,215.372093,260.0
17,1992_KENTUCKY,KENTUCKY,1992,922462.074844,2642902.0,289902.0,1643109.0,709891.0,2518082.0,1343438.0,...,49666.0,49993.0,38029.0,577954.717647,281331.857843,655041.0,215.000000,262.000000,213.000000,260.0
18,1992_LOUISIANA,LOUISIANA,1992,922462.074844,3341253.0,367822.0,1848734.0,1124697.0,3362853.0,1888349.0,...,61125.0,55942.0,38368.0,577954.717647,281331.857843,797985.0,204.000000,250.000000,204.000000,260.0
19,1992_MAINE,MAINE,1992,922462.074844,1206819.0,73160.0,511654.0,622005.0,1228869.0,685350.0,...,17154.0,15969.0,13882.0,577954.717647,281331.857843,216453.0,232.000000,279.000000,227.000000,260.0

**(5)** Compare your answers on the second, third and fourth questions. Do you notice a meaningful difference?