# <font color=blue>Assignments for "DataFrame Basics"</font>

1. Create a DataFrame whose index is the first 10 letters of the alphabet and contains two more columns with first 10 prime numbers and the first 10 fibonacci numbers.

In [1]:
import pandas as pd
import numpy as np

def is_prime(num):
  if num > 1: 
      
   # Iterate from 2 to n / 2  
   for i in range(2, num): 
         
       # If num is divisible by any number between  
       # 2 and n / 2, it is not prime  
       if (num % i) == 0: 
         return False
         break
   else: 
       return True
  
  else: 
   return True

    
list=[]    
for i in range(30):
  if is_prime(i):
    list.append(i)
  if len(list)==10:
    break

nterms = 10
# first two terms
n1, n2 = 1, 1
count = 0
list_fib=[]
while count < nterms:
    
    list_fib.append(n1)
    nth = n1 + n2
    # update values
    n1 = n2
    n2 = nth
    count += 1

df=pd.DataFrame()
df['primes']=list
df['fibonnacci']=list_fib
df

   primes  fibonnacci
0       0           1
1       1           1
2       2           2
3       3           3
4       5           5
5       7           8
6      11          13
7      13          21
8      17          34
9      19          55